[WIP] Announcing Cucumber-JVM v3.0.0
cucumber-attic/website pull request #290
Opened 2018-05-04 15:39 UTC by mpkorstanje

Announcing Cucumber-JVM v3.0.0

2018-05-04 20:17 UTC, aslakhellesoy requested changes
Great blog post @mpkorstanje - just go ahead and publish it yourself when you'vew reviewed my feedback.

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +Cucumber expressions have been implemented! This required a fairly involved refactoring that necessitated the removal
Can you say redesign rather than refactoring? (A refactoring only takes 10 seconds - this took 10 months) :-P

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +Cucumber expressions have been implemented! This required a fairly involved refactoring that necessitated the removal
s/necessitated/required/

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +of XStream and prompted a rewrite of Data Tables. It was also one of the reasons that has prompted us to drop support
Most Cucumber users have no idea what XStream is, so I'd just leave it out.

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +for several the less used languages.
I think we should link to the other blog post, and just publish it on the same day.

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +Cucumber expressions have been implemented! This required a fairly involved refactoring that necessitated the removal
Maybe add: 

Cucumber Expressions [were introduced](https://cucumber.io/blog/2017/07/26/announcing-cucumber-expressions) nearly a year ago in Cucumber.rb and Cucumber.js.

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +public class ParameterTypes implements Configuration {
Call this `DataTableTypes`?

I assume it's OK to more than one `cucumber.api.Configuration` implementation? Can you mention that explicitly?

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +This may look a bit tedious. But you can also use your favourite object mapper instead.
What exactly is an object mapper? Is it a category of libraries (Jackson, ModelMapper etc)?

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +ObjectMapper objectMapper = new ObjectMapper();
Is this a made-up class name for some generic object mapper? If it's not made up, can you make it explicit what library this is from?

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +
Can you add one paragraph?

Cucumber 1.x and 2.x used a library called XStream as a central building block for both data tables and type conversion.

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +
Can you add:

We're not providing a migration guide in this blog post. If you have a specific question about how to migrate, please [contact us](https://cucumber.io/support) and we'll update the documentation accordingly.

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +Prior to Cucumber Expressions XStream was used internally to handle all conversions from Strings to Objects. However the
As suggested above, this would be a good intro to this section for people who don't know about XStream.

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +also problem in term.
?

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +With the introduction of Cucumber Expressions half of the usecase for XStream disapeared. It wasn't realistic to use
disappeared

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +To support the invoke around semantics the TestStep event has been replaced with an interface. And it's concrete
its

2018-05-04 20:17 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +When doing a dry run all hooks will be reported. In prior implementations the before and after scenario hooks were
reported, but not executed right?

2018-05-11 21:16 UTC, mpkorstanje commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +public class ParameterTypes implements Configuration {
Can't have more then one. There can only be one type registry. And it needs a language to be created. Maybe rethinking the naming of configuration? TypeRegistryConfiguration?

2018-05-11 21:17 UTC, mpkorstanje commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +This may look a bit tedious. But you can also use your favourite object mapper instead.
Yes. In short, any library that maps objects to maps or the other way around. Most also map to json.

2018-05-11 21:40 UTC, mpkorstanje commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +also problem in term.
That should be ...also a problem in the long term. This is a really quick draft. :D

If you were talking about the XStream stuff:

Say you have a rest API. Spring boot and other frameworks let you define end points as java methods:

```java
    @RequestMapping("/greeting")
    public Greeting greeting(@RequestParam(value="name", defaultValue="World") Person person) {
        return new Greeting(counter.incrementAndGet(), String.format(template, person.getName()));
    }
```

If you want to test this from Cucumber you have define how the Person object is created. This may be done through a data table. While the conversion in this example is straightforward, in practice POJO's are usually annotated with hints for the object mapper.  Typically about date/time formats, alternative property names, custom transformers, ect.

XStream doesn't understand these hints. So now you can either annotate the POJO with XStream annotations, this puts Cucumber into production scope - somewhat undesirable. Or you can define an `XStreamConverter` for the POJO. But this means you're doing everything by hand again and not reusing the POJO.

2018-05-11 21:48 UTC, mpkorstanje commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +also problem in term.
This will come with some potential for future improvement. Spring will apply some configuration to the object mapper. So eventually it might be desirable to define parameter and data table types in the same way steps are defined. This allows DI, which will allow the parameter types access to the object mapper configured by spring.

2018-05-11 23:47 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +public class ParameterTypes implements Configuration {
Yes, let's rename it to `TypeRegistryConfiguration`. If we want to add other kinds of configuration later, that can be in a different interface. That makes it easier for people to only implement the configuration they care about.

2018-05-11 23:48 UTC, aslakhellesoy commented on apps/dynamic/views/_posts/announcing-cucumber-jvm-3-0-0.md
> +This may look a bit tedious. But you can also use your favourite object mapper instead.
Ok, can you call it "object mapper library" then?

2018-05-11 23:48 UTC, aslakhellesoy approved these changes

2018-05-19 18:28 UTC, merged