Blog post: 10 year birthday mobathon
cucumber-attic/website pull request #315
Opened 2018-10-05 16:13 UTC by mattwynne

2018-10-05 16:16 UTC, mattwynne commented
@mlvandijk @aslakhellesoy @jaysonesmith could you have a look at the post (preview [here](https://cucumber-website-pr-315.herokuapp.com/blog/2018/10/04/cucumber-10-year-mobathon)) and let me know any more lessons I can put in that spring to mind?

2018-10-05 16:18 UTC, jaysonesmith commented
Sure :)

2018-10-05 18:08 UTC, jaysonesmith commented
The environment stuff would be one of the biggest things to handle. Perhaps having either a faster build cycle (which I want to take a stab at) or a transfer to a different project while that's going could help down time? With that said though, using the downtime to chat and build camaraderie is also a great thing. /shrug

Aside from that, you've got two carriage returns before the last section starting with, "I still have a crazy idea that" and Björn's name has a standard o in it instead of ö.

I had an absolutely fantastic time though and would love to keep doing it!

2018-10-05 18:12 UTC, mxygem requested changes

2018-10-05 18:12 UTC, jaysonesmith commented on apps/dynamic/views/_posts/cucumber-10-year-mobathon.md
> +Having a goal for the session helped a great deal, and we quickly reached agreement about what to focus on. Aslak had done his homework ahead of time and we had a nice small problem to get our teeth
Missing ö in Björn's name.

2018-10-05 20:16 UTC, mattwynne commented
Hee hee can I quote you on that?

Typed with my Thumbs.

> On 5 Oct 2018, at 19:08, Jayson Smith <notifications@github.com> wrote:
> 
> I had an absolutely fantastic time though and would love to keep doing it

-- 


Inspiring meaningful, effective collaboration in every software delivery 
organisation.





The Cucumber logo is the intellectual property of 
Cucumber Ltd, a limited company registered in Scotland, number 456793.



Registered address: Cucumber Ltd, The Melting Pot, 5 Rose Street, Edinburgh 
EH2 2PR, Scotland, United Kingdom.
CONFIDENTIALITY NOTICE: The information 
in this e-mail is confidential and privileged; it is intended for use 
solely by the individual or entity named as the recipient hereof. 
Disclosure, copying, distribution, or use of the contents of this e-mail by 
persons other than the intended recipient is strictly prohibited and may 
violate applicable laws. If you have received this e-mail in error, please 
delete the original message and notify us by email immediately. Thank you. 
Cucumber Ltd.

2018-10-05 21:49 UTC, jaysonesmith commented
@mattwynne Yeah, absolutely! Do you want something more? How's:

"The anniversary mobathon was an absolutely fantastic time and I would love to do it more! Driving the code changes while having the guidance of folks already familiar with the code enabled me to do things for the first time(like release various Cucumber Ruby gems) that I wouldn't have been able to on my own. What a wonderful experience in so many ways!"

2018-10-06 04:44 UTC, mlvandijk reviewed
Great post overall. Possible addition would be to mention the word doc / picture drawn to explain how things worked (and tools used). That really helped clarify things for me and even if I didn't get to actively participate I still learned a lot. Also, I'd love for that picture/info to find it's way into documentation somewhere.

2018-10-06 04:44 UTC, mlvandijk commented on apps/dynamic/views/_posts/cucumber-10-year-mobathon.md
> +----
This renders as additional whitespace which looks weird to me. Just remove it?

2018-10-06 04:46 UTC, mlvandijk commented on apps/dynamic/views/_posts/cucumber-10-year-mobathon.md
> +----
Also, created this issue based on discussions during the mob, in case we want to solve it / link to it: https://github.com/cucumber/docs.cucumber.io/issues/233

2018-10-09 23:15 UTC, mxygem approved these changes

2018-10-09 23:17 UTC, jaysonesmith commented
Not sure if you want to tackle the formatting at the end, but either way LGTM!

2018-10-22 14:38 UTC, mlvandijk approved these changes

2018-10-22 20:58 UTC, mattwynne commented
Merged in 1fc562f73b775f110330a1835a946d40a1433dfd 94e92f3032a1454e08252d57c44f45a6c98233d2 21b0da1292fdef4fefa256dda823c6350ad2a5b4 2921cd75457cd6cf6f88e5f055cf20561fb95d5e

2018-10-22 20:58 UTC, closed without merging